import type { Metadata } from 'next';
import { pretendardRegular, pretendardBold } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendardRegular.variable} ${pretendardBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
